spring:
  application:
    name: devtrack-api

  # PostgreSQL Configuration
  datasource:
    url: jdbc:postgresql://localhost:5432/devtrack_db
    username: postgres
    password: ${DB_PASSWORD}

  # JPA / Hibernate Configuration
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true